# --- SIMULATION PARAMETERS ---
WORLD_SIZE = 40
STARTING_POPULATION = 30
STARTING_FOOD = 50

# --- ENERGY PARAMETERS ---
STARTING_ENERGY = 100.0
ENERGY_GAIN_FOOD = 50.0
ENERGY_COST_MOVE = 0.5
ENERGY_COST_REPRODUCE = 60.0
REPRODUCE_ENERGY_THRESHOLD = 120.0
HUNGER_THRESHOLD = 70.0

# --- GENETIC PARAMETERS ---
MUTATION_RATE = 0.05        # 5% chance per gene
MUTATION_RATE_META = 0.01   # 1% chance for the meta-gene to mutate

# --- HAWK-DOVE ESS PARAMETERS ---
AGGRESSION_THRESHOLD = 0.5 # Above this, vehicle *acts* as a HAWK
RESOURCE_VALUE = ENERGY_GAIN_FOOD
FIGHT_COST = 80.0
DISPLAY_COST = 5.0